# Generated by Django 3.2.4 on 2021-07-12 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='apitestdesc',
            field=models.CharField(max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=64, verbose_name='接口名称')),
                ('apiurl', models.CharField(max_length=200, verbose_name='请求URL地址')),
                ('apiparamvalues', models.CharField(max_length=800, verbose_name='请求参数值')),
                ('apimothod', models.CharField(choices=[('0', 'get'), ('1', 'post'), ('2', 'put'), ('3', 'delete'), ('4', 'path')], default='0', max_length=200, null=True, verbose_name='请求方法')),
                ('apiresult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('apistatus', models.BooleanField(verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '单一场景接口',
                'verbose_name_plural': '单一场景接口',
            },
        ),
    ]
